name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  BackEnd:
    runs-on: ubuntu-latest

    steps:
    - name: Check Source
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Set up Node.js for BackEnd
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install BackEnd dependencies
      run: |
        cd BackEnd
        npm install

    - name: Deploy BackEnd to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: SickTick
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_BackEnd_PUBLISH_PROFILE }}
