name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  BackEnd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          cd BackEnd
          npm install
        
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: SickTick
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .